print ('APPLICATION FORM')
print ("Dear Valued Clint Kindly")
input ('Enter Your Sex Male/Female:') 
print ('Hello', input ('Enter Your Title Mr / Ms / Miss ?') , input ('Enter Your First Name:') , input ('Enter Your Middle Name:') , input ('Enter Your Last Name:'))
input ('Enter Your Age:') , input ('Enter Your Marital Status:')
print ('Contact Information')
input ('Enter Your Home Address:'), input ('Enter Your Mobile:') , input ('Enter Your Home Telephone:'), input ('Enter Your Office Telephone:') , input ('Enter Your Email:')
print ('Education Information')
input ('Enter Your Your Faculty Name:') , input ('Enter Your Collage Name:') , input ('Enter Your major Field:') ,input ('Enter your Graduation Year:')
print ('Thanks for your valued answers and one of our reprsentitive will be with you whitin few minutes')